server:
  port: 9004
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'
spring:
  application:
    name: jt_cards
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    username: cards
    password: 12345
    url: jdbc:h2:mem:jt_cardsdb

info:
  app:
    version: 0.0.1
    description: Java Express Cards MS
  contact: +91-7286838838

