server:
  port: 9003
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'
spring:
  application:
    name: jt_accounts
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    username: accounts
    password: 12345
    url: jdbc:h2:mem:jt_accountsdb

info:
  app:
    version: 0.0.1
    description: Java Express Accounts MS
  contact: +91-7286838838


