server:
  port: 9003
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
spring:
  application:
    name: jt-accounts
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    username: accounts
    password: 12345
    url: jdbc:h2:mem:jt-accountsdb
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    prefer-ip-address: true
info:
  app:
    version: 0.0.1
    description: Java Express Accounts MS
  contact: +91-7286838838
logging:
  pattern:
    level: '%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]'
